all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.sample1/Hello
#	java -classpath "../.." s4.sample1/Frequencer
#	java -classpath "../.." s4.sample1/InformationEstimator
	java -classpath "../.." s4.sample1/TestCase
