all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173350/Hello
#	java -classpath "../.." s4.b173350/Frequencer
#	java -classpath "../.." s4.b173350/InformationEstimator
	java -classpath "../.." s4.b173350/TestCase
