all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173325/Hello
#	java -classpath "../.." s4.b173325/Frequencer
#	java -classpath "../.." s4.b173325/InformationEstimator
	java -classpath "../.." s4.b173325/TestCase
