all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173344/Hello
#	java -classpath "../.." s4.b173344/Frequencer
#	java -classpath "../.." s4.b173344/InformationEstimator
	java -classpath "../.." s4.b173344/TestCase
