all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.t000000/Hello
#	java -classpath "../.." s4.t000000/Frequencer
#	java -classpath "../.." s4.t000000/InformationEstimator
	java -classpath "../.." s4.t000000/TestCase
