all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173331/Hello
#	java -classpath "../.." s4.b173331/Frequencer
#	java -classpath "../.." s4.b173331/InformationEstimator
	java -classpath "../.." s4.b173331/TestCase
