all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b151816/Hello
#	java -classpath "../.." s4.b151816/Frequencer
#	java -classpath "../.." s4.b151816/InformationEstimator
	java -classpath "../.." s4.b151816/TestCase
