all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173374/Hello
#	java -classpath "../.." s4.b173374/Frequencer
#	java -classpath "../.." s4.b173374/InformationEstimator
	java -classpath "../.." s4.b173374/TestCase
