all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173305/Hello
#	java -classpath "../.." s4.b173305/Frequencer
#	java -classpath "../.." s4.b173305/InformationEstimator
	java -classpath "../.." s4.b173305/TestCase
