all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.sample2/Hello
#	java -classpath "../.." s4.sample2/Frequencer
#	java -classpath "../.." s4.sample2/InformationEstimator
	java -classpath "../.." s4.sample2/TestCase
