all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173370/Hello
#	java -classpath "../.." s4.b173370/Frequencer
#	java -classpath "../.." s4.b173370/InformationEstimator
	java -classpath "../.." s4.b173370/TestCase
