all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.sample0/Hello
#	java -classpath "../.." s4.sample0/Frequencer
#	java -classpath "../.." s4.sample0/InformationEstimator
	java -classpath "../.." s4.sample0/TestCase
