all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173372/Hello
#	java -classpath "../.." s4.b173372/Frequencer
#	java -classpath "../.." s4.b173372/InformationEstimator
	java -classpath "../.." s4.b173372/TestCase
