all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173330/Hello
#	java -classpath "../.." s4.b173330/Frequencer
#	java -classpath "../.." s4.b173330/InformationEstimator
	java -classpath "../.." s4.b173330/TestCase
