all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173311/Hello
#	java -classpath "../.." s4.b173311/Frequencer
#	java -classpath "../.." s4.b173311/InformationEstimator
	java -classpath "../.." s4.b173311/TestCase
