all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b141837/Hello
#	java -classpath "../.." s4.b141837/Frequencer
#	java -classpath "../.." s4.b141837/InformationEstimator
	java -classpath "../.." s4.b141837/TestCase
