all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173376/Hello
#	java -classpath "../.." s4.b173376/Frequencer
#	java -classpath "../.." s4.b173376/InformationEstimator
	java -classpath "../.." s4.b173376/TestCase
