all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173378/Hello
#	java -classpath "../.." s4.b173378/Frequencer
#	java -classpath "../.." s4.b173378/InformationEstimator
	java -classpath "../.." s4.b173378/TestCase
