all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173371/Hello
#	java -classpath "../.." s4.b173371/Frequencer
#	java -classpath "../.." s4.b173371/InformationEstimator
	java -classpath "../.." s4.b173371/TestCase
